POSApplication/Models/Secu_User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace POSApplication.Models
{
    public class Secu_User
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "User Name")]
        public string UserName { get; set; }

        [Required]
        public string Password { get; set; }
        public string Salt { get; set; }

        [Display(Name = "Full Name")]
        public string UserFullName { get; set; }

        [Display(Name = "Phone")]
        public string Phone { get; set; }

        [Display(Name = "Email")]
        public string Email { get; set; }

        [Display(Name = "Address")]
        public string Address { get; set; }
        
        [Display(Name = "Is Admin")]
        public bool IsAdmin { get; set; }

        [Required]
        [Display(Name = "User Status")]
        public string UserStatus { get; set; }

        [Display(Name = "Last Login")]
        public DateTime? LastLoginDate { get; set; }
        public int? InvalidAttempt { get; set; }

        [Display(Name = "Role Name")]
        [ForeignKey("Secu_Role")]
        public int? RoleId { get; set; }
        public virtual Secu_Role Secu_Role { get; set; }



        //public bool? IsSuperAdmin { get; set; }
        

    }
}

POSApplication/Controllers/Secu_UserController.cs
using POSApplication.Helpers;
using POSApplication.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace POSApplication.Controllers
{
    [Authorize]
    public class Secu_UserController : Controller
    {
        private POSDBContext db = new POSDBContext();
        private EncryptionDecryptionUtil encryptionDecryptionUtil = new EncryptionDecryptionUtil();
        private int saltLength = 5;

        // GET: Secu_User
        public ActionResult Index()
        {
            var IsAdmin = Convert.ToBoolean(Session["IsAdmin"].ToString());

            if (IsAdmin)
            {
                return View(db.Secu_User.ToList());
            }
            else
            {
                return View(db.Secu_User.Where(x => x.IsAdmin == null || x.IsAdmin == false).ToList());
            }

        }

        // GET: Secu_User/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Secu_User secu_User = db.Secu_User.Find(id);
            if (secu_User == null)
            {
                return HttpNotFound();
            }
            return View(secu_User);
        }



        // GET: Secu_User/Create
        public ActionResult Create()
        {
            ViewBag.UserStatus = new SelectList(new List<SelectListItem> { new SelectListItem { Text = "Inactive", Value = "0" }, new SelectListItem { Text = "Active", Value = "1" } }, "Value", "Text");
            ViewBag.RoleId = new SelectList(db.Secu_Role, "Id", "Name");
          

            return View();
        }

        


        public JsonResult SaveUser(Secu_User User)
        {
            var result = new
            {
                flag = false,
                message = "Error occured. !",
                Id = 0
            };

            try
            {
                var OpDate = DateTime.Now;
                using (var dbContextTransaction = db.Database.BeginTransaction())
                {
                    try
                    {
                        string salt = encryptionDecryptionUtil.GenerateSalt(saltLength);

                        //-------


                        var user = new Secu_User()
                        {
                            Id = User.Id,
                            UserName = User.UserName,
                            UserStatus = User.UserStatus,
                            Phone = User.Phone,
                            Email = User.Email,
                            //Password = User.Password,
                            Salt = salt,
                            Password = encryptionDecryptionUtil.CreatePasswordHash(User.Password, salt),
                          
                            UserFullName = User.UserFullName,
                            RoleId = User.RoleId,
                            IsAdmin = User.IsAdmin
                        };


                        //db.Entry(user).State = EntityState.Added;
                        db.Secu_User.Add(user);
                        db.SaveChanges();

                        TempData["myData"] = user.Id;
                        //-------------------



                        dbContextTransaction.Commit();

                        result = new
                        {
                            flag = true,
                            message = "Saving successful !!",
                            Id = user.Id
                        };

                        //Success("Record saved successfully.", true);


                    }
                    catch (Exception ex)
                    {
                        dbContextTransaction.Rollback();

                        result = new
                        {
                            flag = false,
                            message = ex.Message,
                            Id = 0
                        };
                    }
                }

            }
            catch (Exception ex)
            {

                result = new
                {
                    flag = false,
                    message = ex.Message,
                    Id = 0
                };
            }


            return Json(result, JsonRequestBehavior.AllowGet);
        }



        public JsonResult ChangePassword(int userid, string pass)
        {
            var result = new
            {
                flag = false,
                message = "Error occured. !",
                Id = 0
            };

            try
            {
                var OpDate = DateTime.Now;
                using (var dbContextTransaction = db.Database.BeginTransaction())
                {
                    try
                    {
                        Secu_User user = db.Secu_User.Find(userid);

                        user.Salt = encryptionDecryptionUtil.GenerateSalt(saltLength);
                        user.Password = encryptionDecryptionUtil.CreatePasswordHash(pass, user.Salt);


                        //user.Password = pass;
                        db.Entry(user).State = EntityState.Modified;
                        //db.Secu_User.Add(user);
                        db.SaveChanges();

                        dbContextTransaction.Commit();

                        result = new
                        {
                            flag = true,
                            message = "Saving successful !!",
                            Id = user.Id
                        };
                    }
                    catch (Exception ex)
                    {
                        dbContextTransaction.Rollback();

                        result = new
                        {
                            flag = false,
                            message = ex.Message,
                            Id = 0
                        };
                    }
                }
            }
            catch (Exception ex)
            {

                result = new
                {
                    flag = false,
                    message = ex.Message,
                    Id = 0
                };
            }
            return Json(result, JsonRequestBehavior.AllowGet);

        }



        public JsonResult UpdateUser(Secu_User User)
        {
            var result = new
            {
                flag = false,
                message = "Error occured. !",
                Id = 0,
                isRedirect = false
            };

            try
            {
                var OpDate = DateTime.Now;
                using (var dbContextTransaction = db.Database.BeginTransaction())
                {
                    try
                    {

                        //var user = new Secu_User()
                        //{
                        //    Id = User.Id,
                        //    UserName = User.UserName,
                        //    UserStatus = User.UserStatus,
                        //    UserFullName = User.UserFullName,
                        //    TeamId = User.TeamId,
                        //    DesignationId = User.DesignationId,
                        //    IsAdmin = User.IsAdmin
                        //};
                        
                        var userId = Convert.ToInt32(Session["uid"]);

                        var user = db.Secu_User.Find(User.Id);


                        user.UserName = User.UserName;
                        user.UserFullName = User.UserFullName;
                        user.Phone = User.Phone;
                        user.Email = User.Email;
                        user.UserStatus = User.UserStatus;
                        user.RoleId = User.RoleId;
                        user.IsAdmin = User.IsAdmin;
              

                        db.Entry(user).State = EntityState.Modified;

                        //db.Secu_User.Add(user);
                        db.SaveChanges();

                        dbContextTransaction.Commit();

                   

                        if (user.Id == userId)
                        {
                            result = new
                            {
                                flag = true,
                                message = "Saving successful !!",
                                Id = user.Id,
                                isRedirect = true
                            };

                        }
                        else
                        {
                            result = new
                            {
                                flag = true,
                                message = "Saving successful !!",
                                Id = user.Id,
                                isRedirect = false
                            };
                        }


                        //result = new
                        //{
                        //    flag = true,
                        //    message = "Saving successful !!",
                        //    Id = user.Id
                        //};

                        //Success("Record saved successfully.", true);
                        return Json(result, JsonRequestBehavior.AllowGet);

                    }
                    catch (Exception ex)
                    {
                        dbContextTransaction.Rollback();

                        result = new
                        {
                            flag = false,
                            message = ex.Message,
                            Id = 0,
                            isRedirect = false
                        };

                        return Json(result, JsonRequestBehavior.AllowGet);
                    }
                }

            }
            catch (Exception ex)
            {

POSApplication/Views/Secu_User/Create.cshtml
@model POSApplication.Models.Secu_User
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-primary panel-bordered">
    <div class="panel-heading">
        <h5 class="panel-title">User Information</h5>
    </div>
    <div class="panel-body">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group form-group-xs">
                            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group form-group-xs">
                            @Html.LabelFor(model => model.UserStatus, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.DropDownList("UserStatus", null, "", htmlAttributes: new { @class = "form-control select2 input-xs" })
                                @Html.ValidationMessageFor(model => model.UserStatus, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group form-group-xs">
                            @Html.LabelFor(model => model.LastLoginDate, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.TextBox("LastLoginDate", null, new { @class = "form-control", @disabled = "disabled" })
                                @Html.ValidationMessageFor(model => model.LastLoginDate, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group form-group-xs">
                            @Html.LabelFor(model => model.UserFullName, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.UserFullName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.UserFullName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group form-group-xs">
                            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group form-group-xs">
                            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group form-group-xs">
                            @Html.LabelFor(model => model.RoleId, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.DropDownList("RoleId", null, "", htmlAttributes: new { @class = "form-control select2 input-xs" })
                                @Html.ValidationMessageFor(model => model.RoleId, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group form-group-xs">
                            @Html.LabelFor(model => model.IsAdmin, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.CheckBoxFor(model => model.IsAdmin, new { @class = "IsAdmin" })
                                @Html.ValidationMessageFor(model => model.IsAdmin, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    @*<div class="col-md-4">
                        <div class="form-group form-group-xs">
                            @Html.LabelFor(model => model.CompanyUnitId, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.DropDownList("CompanyUnitId", null, "", htmlAttributes: new { @class = "form-control select2 input-xs" })
                                @Html.ValidationMessageFor(model => model.CompanyUnitId, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>*@
                </div>
            </div>
        }

    </div>
</div>
<div class="form-group" style="padding-top:20px;">
    @using (Html.BeginForm("ImageUpload", "Secu_User", FormMethod.Post, new { enctype = "multipart/form-data", @id = "myform" }))
            {
        <div class="col-lg-12">
            <input type="hidden" value="" id="UId" name="UId" />
            <div class="col-lg-2"><select id="ImageType" name="ImageType" class="select2"><option value="1">User Photo</option><option value="2">Signature</option></select></div>
            <div class="col-lg-4">
                <input type="file" name="postedFiles" id="postedFiles" />
            </div>
        </div>
        @*<input type="file" name="postedFiles" id="postedFiles" multiple="multiple" />*@ @*For uploading multiple files*@
      
        <input type="submit" value="Upload" style="visibility:hidden;" id="submit" class="btn-primary" />
    }
</div>

<div class="panel panel-primary panel-bordered">

    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-bordered table-xxs">
                <tbody>
                    <tr>
                        <td class="col-lg-2">Password</td>
                        <td class="col-lg-5"><input type="password" id="Password" name="Password" class="form-control input-xs" /></td>
                        <td class="col-lg-5">&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="col-lg-2">Re-Type Password</td>
                        <td class="col-lg-5"><input type="password" id="RePassword" name="RePassword" class="form-control input-xs" /></td>
                        <td class="col-lg-5">&nbsp;</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>


<div class="panel panel-primary panel-bordered">
    <div class="panel-body">
        <div class="form-group">
            <div class="col-md-12">
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
                <button type="button" class="btn btn-success" id="saveState">Save <i class="icon-arrow-right14 position-right"></i></button>
            </div>
        </div>

    </div>
</div>



@section Scripts {


    <script type="text/javascript">

        function RebindDatePicker() {
            $('.datepicker').datepicker("destroy");
            $('.datepicker').datepicker({
                format: 'dd/mm/yyyy',
                todayHighlight: true,
                todayBtn: true,
                autoclose: true
            });

        }

        $(document).ready(function () {
            //$('body').addClass("sidebar-xs");
            $(".select2").select2();
            $('.datepicker').datepicker({
                format: 'dd/mm/yyyy',
                todayHighlight: true,
                todayBtn: true,
                autoclose: true
            });
            // jquery validator bug fix using moment
            $.validator.methods.date = function (value, element) {
                return this.optional(element) || moment(value, "DD/MM/YYYY", true).isValid();
            }

        });


        $('#RePassword').change(function () {
            var passs = $('#Password').val();
            var rePass = $(this).val();

            if (passs != rePass) {
                alert("Password doesn't match!");
                $(this).val("");
            }
        });





        $('#saveState').click(function () {

            if ($.trim($('#UserName').val()) === "") {
                alert('UserName required');
                $('#UserName').focus();
            }
           
            else if ($.trim($('#RoleId').val()) === "") {
                alert('Role required');
                $('#RoleId').focus();
            }
            else if ($.trim($('#Password').val()) === "") {
                alert('Password required');
                $('#Password').focus();
            }
            else if ($.trim($('#Password').val()) != "" && $('#RePassword').val == "") {
                alert("Please confirm password!");
            }
            else {
                SaveUserData();
            }

        });

        function SaveUserData() {

            $("#saveState").attr("disabled", "disabled");


            var UserName = $.trim($('#UserName').val());
            var UserStatus = $('#UserStatus').val();
            var UserFullName = $('#UserFullName').val();
            var Phone = $('#Phone').val();
            var Email = $('#Email').val();
            var Password = $('#Password').val();
            var RoleId = $('#RoleId').val();
      
            var IsAdmin = 0;
            if ($('#IsAdmin').is(":checked")) {
                IsAdmin = 1;
            }
            else {
                IsAdmin = 0;
            }




            Secu_Users = JSON.stringify({
                Id: 0,
                UserName: UserName,
                UserStatus: UserStatus,
                UserFullName: UserFullName,
                Phone: Phone,
                Email:Email,
                Password: Password,
                RoleId: RoleId,
                IsAdmin: IsAdmin,
               
            });


            $.ajax({
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                type: 'POST',
                url: '/Secu_User/SaveUser',
                data: Secu_Users,
                success: function (result) {
                    console.log(result);
                    $("#saveState").removeAttr("disabled");
                    if (result.flag == true) {
                        $("#UserId").val(result.Id);
                        //alert(result.Id);
                        $('#submit').click();

                        //swal("Record save successfully!","success");
                        alert("Record save successfully!");
                        //window.location = "/Secu_User/Index";
                    }
                    else {
                        alert(result.message);
                    }

                },
                error: function (jqXHR, textStatus, errorThrown) {
                    alert('Error: ' + textStatus + ' - ' + errorThrown);
                    $("#saveState").removeAttr("disabled");
                }
            });

        }


    </script>
}

POSApplication/Views/Secu_User/Index.cshtml
@model IEnumerable<POSApplication.Models.Secu_User>
@using POSApplication.Helper

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

    POSApplication.Models.POSDBContext db = new POSApplication.Models.POSDBContext();

}

<div class="panel panel-default">
    <div class="panel-heading"><b>User  List</b></div>



    <div class="panel-body">
        <p>
            @Html.ActionLink("Create", "Create", null, new { @class = "btn btn-success" })
        </p><br>

   
            <table id="datatable"class="table table-responsive table-bordered datatable1  datatable-show-all">
                <thead>
                    <tr class="bg-blue">
                        <th class="col-lg-2">
                            @Html.DisplayNameFor(model => model.UserName)
                        </th>
                        <th class="col-lg-1">
                            @*@Html.DisplayNameFor(model => model.RoleId)*@
                            Role
                        </th>
                        <th class="col-lg-1">
                            @*@Html.DisplayNameFor(model => model.IsAdmin)*@
                            Admin
                        </th>
                        <th class="col-lg-1">
                            @*@Html.DisplayNameFor(model => model.UserStatus)*@
                            Status
                        </th>
                        <th class="col-lg-2">
                            Company
                        </th>
                        <th class="col-lg-2">
                            @Html.DisplayNameFor(model => model.LastLoginDate)
                        </th>
                       

                        <th class="col-lg-2">

                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.UserName)
                            </td>
                            <td>
                                @{
                                    var roleCheck = db.Secu_Role.FirstOrDefault(x => x.Id == item.RoleId);
                                    var roleName = "";

                                    if (roleName == null)
                                    {
                                        roleName = "";
                                    }
                                    else
                                    {
                                        roleName = roleCheck.Name;
                                    }
                                }
                                <label>@roleName</label>
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.IsAdmin)
                            </td>
                            <td align="center">
                                @{
                                    if (item.UserStatus == "1")
                                    {
                                        <span class="badge badge-success">Active</span>
                                    }
                                    else
                                    {
                                        <span class="badge badge-warning">Inactive</span>
                                    }
                                }
                                @*@Html.DisplayFor(modelItem => item.UserStatus)*@
                            </td>
                            <td></td>
                            <td>
                                @NullHelper.GetPrettyDate(DateTime.Now.AddMinutes(-(DateTime.Now.Subtract((item.LastLoginDate ?? DateTime.Now)).TotalMinutes)))
                                @*@item.LastLoginDate*@
                            </td>
                          
                            <td>
                           
                                @Html.ActionLink(" ", "Edit", new { Id = item.Id }, new { @class = "btn btn-xs-info  glyphicon glyphicon-pencil", @title = "Edit" })
                                @*@Html.ActionLink(" ", "Details", new { Id = item.Id }, new { @class = "btn btn-xs text-info  icon-file-text2", @title = "Details" })*@
                                <a class="btn btn-xs labeled btn-danger" title="Delete" href="javascript:deleteFunction(@item.Id)"><i class="glyphicon glyphicon-remove"></i>   </a>
                            </td>
                        </tr>
                                    }

                </tbody>
            </table>
        </div>
    </div>



    @section scripts
{
        @*@Scripts.Render("~/bundles/jqueryval")*@

        <script>
            //$(".select2").select2();
            $("#datatable").DataTable();
            function deleteFunction(Id) {
                var Con = confirm("are you sure want to delete this ?");
                if (Con == true) {
                    $.ajax({
                        url: "/Secu_User/DeleteItem",
                        type: "post",
                        data: {
                            Id: Id
                        },
                        dataType: "json",

                        success: function (flag) {
                            console.log(flag);

                            if (flag.flag == true) {
                                alert("Successfully deleted !");
                                window.location = "/Secu_User/Index";
                            } else {
                                alert(flag.message);
                            }
                        },

                        error: function (xhr) {
                            alert('error');

                        }


                    });
                }

            }
        </script>
    }